using System.Text.Json;
using System.Text.RegularExpressions;
using Blazor_Personal_Site.Models;
using Markdig;

namespace Blazor_Personal_Site.Services;

/// <summary>
/// Fetches and caches build data from the Broomfields/PS-CMS-Builds GitHub repository,
/// which is used as a headless CMS. The manifest.json is generated by a GitHub Action
/// that extracts front matter from each build's markdown file.
/// </summary>
public class CadBuildsService
{
    private const string RepoOwner  = "Broomfields";
    private const string RepoName   = "PS-CMS-Builds";
    private const string Branch     = "main";
    private const string RawBase     = $"https://raw.githubusercontent.com/{RepoOwner}/{RepoName}/{Branch}";
    // The manifest is published as a GitHub Release asset, not committed to the branch.
    // Release assets are served from the releases/latest/download path.
    private const string ManifestUrl = $"https://github.com/{RepoOwner}/{RepoName}/releases/latest/download/manifest.json";

    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };

    private static readonly MarkdownPipeline MarkdownPipeline =
        new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();

    private readonly IHttpClientFactory _httpClientFactory;
    private readonly ILogger<CadBuildsService> _logger;

    // Manifest cache
    private BuildManifest? _manifestCache;
    private DateTime _manifestCachedAt = DateTime.MinValue;
    private static readonly TimeSpan ManifestTtl = TimeSpan.FromMinutes(5);

    // Per-build / per-subpage markdown cache (slug or "slug/subpage" → rendered HTML)
    // Version token: bump this when the HTML post-processing pipeline changes
    // (e.g. WrapImages, RewriteRelativeLinks added) so stale cached HTML is never served.
    private const int HtmlCacheVersion = 3;
    private readonly Dictionary<string, (string Html, DateTime CachedAt, int Version)> _htmlCache = new();
    private static readonly TimeSpan HtmlTtl = TimeSpan.FromMinutes(10);

    // Sub-page title cache ("slug/subpage" → title string extracted from frontmatter)
    private readonly Dictionary<string, (string Title, DateTime CachedAt)> _subpageTitleCache = new();

    public CadBuildsService(IHttpClientFactory httpClientFactory, ILogger<CadBuildsService> logger)
    {
        _httpClientFactory = httpClientFactory;
        _logger = logger;
    }

    // ── URL helpers ──────────────────────────────────────────────────────────

    /// <summary>
    /// Resolves a relative asset path (as stored in the manifest or markdown) to
    /// a full GitHub CDN URL. For example, "02-model-cap.jpeg" for slug
    /// "rocket-booster-bracket" becomes:
    ///   https://raw.githubusercontent.com/…/main/builds/rocket-booster-bracket/02-model-cap.jpeg
    /// </summary>
    public string ResolveCdnUrl(string slug, string relativePath)
    {
        relativePath = relativePath.TrimStart('.', '/');
        return $"{RawBase}/builds/{Uri.EscapeDataString(slug)}/{relativePath}";
    }

    // ── Public fetch methods ─────────────────────────────────────────────────

    /// <summary>
    /// Fetches (and caches) the manifest. Returns null if the fetch fails.
    /// </summary>
    public async Task<BuildManifest?> FetchManifestAsync()
    {
        if (_manifestCache is not null && DateTime.UtcNow - _manifestCachedAt < ManifestTtl)
            return _manifestCache;

        try
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            var http = _httpClientFactory.CreateClient();
            var json = await http.GetStringAsync(ManifestUrl, cts.Token);

            if (string.IsNullOrWhiteSpace(json))
            {
                _logger.LogWarning("CAD Builds manifest was empty.");
                return null;
            }

            var manifest = JsonSerializer.Deserialize<BuildManifest>(json, JsonOptions);
            if (manifest is null)
            {
                _logger.LogWarning("CAD Builds manifest deserialised as null.");
                return null;
            }

            _manifestCache = manifest;
            _manifestCachedAt = DateTime.UtcNow;
            return _manifestCache;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to fetch CAD Builds manifest.");
            return null;
        }
    }

    /// <summary>
    /// Fetches, processes, and caches the rendered HTML for a single build's
    /// markdown file. Front matter is stripped, relative image paths are
    /// rewritten to CDN URLs, and the markdown is converted to safe HTML.
    /// Returns null if the fetch fails.
    /// </summary>
    public async Task<string?> FetchBuildHtmlAsync(string slug)
    {
        if (_htmlCache.TryGetValue(slug, out var cached) &&
            cached.Version == HtmlCacheVersion &&
            DateTime.UtcNow - cached.CachedAt < HtmlTtl)
            return cached.Html;

        var url = $"{RawBase}/builds/{Uri.EscapeDataString(slug)}/{slug}.md";
        try
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            var http = _httpClientFactory.CreateClient();
            var raw = await http.GetStringAsync(url, cts.Token);

            var body = StripFrontMatter(raw);
            body = RewriteRelativeImages(body, slug);
            var html = Markdown.ToHtml(body, MarkdownPipeline);
            html = WrapImages(html);
            html = RewriteRelativeLinks(html, slug);

            _htmlCache[slug] = (html, DateTime.UtcNow, HtmlCacheVersion);
            return html;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to fetch build markdown for slug '{Slug}'.", slug);
            return null;
        }
    }

    /// <summary>
    /// Fetches, processes, and caches the rendered HTML for a single sub-page.
    /// Applies the same pipeline as the main build page (front matter stripped,
    /// relative images rewritten, markdown converted, images wrapped).
    /// Returns null if the fetch fails.
    /// </summary>
    public async Task<string?> FetchSubPageHtmlAsync(string slug, string subpage)
    {
        var cacheKey = $"{slug}/{subpage}";

        if (_htmlCache.TryGetValue(cacheKey, out var cached) &&
            cached.Version == HtmlCacheVersion &&
            DateTime.UtcNow - cached.CachedAt < HtmlTtl)
            return cached.Html;

        var url = $"{RawBase}/builds/{Uri.EscapeDataString(slug)}/{subpage}.md";
        try
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            var http = _httpClientFactory.CreateClient();
            var raw = await http.GetStringAsync(url, cts.Token);

            var body = StripFrontMatter(raw);
            body = RewriteRelativeImages(body, slug);
            var html = Markdown.ToHtml(body, MarkdownPipeline);
            html = WrapImages(html);

            _htmlCache[cacheKey] = (html, DateTime.UtcNow, HtmlCacheVersion);
            return html;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to fetch sub-page markdown for '{Slug}/{Subpage}'.", slug, subpage);
            return null;
        }
    }

    /// <summary>
    /// Fetches and caches the <c>title</c> field from a sub-page's YAML front matter.
    /// Used to populate navigation labels without processing the full markdown body.
    /// Returns null if the fetch fails or no title is found in the front matter.
    /// </summary>
    public async Task<string?> FetchSubPageTitleAsync(string slug, string subpage)
    {
        var cacheKey = $"{slug}/{subpage}";

        if (_subpageTitleCache.TryGetValue(cacheKey, out var cached) &&
            DateTime.UtcNow - cached.CachedAt < HtmlTtl)
            return cached.Title;

        var url = $"{RawBase}/builds/{Uri.EscapeDataString(slug)}/{subpage}.md";
        try
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
            var http = _httpClientFactory.CreateClient();
            var raw = await http.GetStringAsync(url, cts.Token);

            var title = ExtractFrontMatterTitle(raw) ?? TitleCaseFromSlug(subpage);
            _subpageTitleCache[cacheKey] = (title, DateTime.UtcNow);
            return title;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to fetch sub-page title for '{Slug}/{Subpage}'.", slug, subpage);
            return null;
        }
    }

    // ── Private helpers ──────────────────────────────────────────────────────

    /// <summary>
    /// Strips the YAML front matter block (--- … ---) from the top of a
    /// markdown string and returns the remaining body content.
    /// </summary>
    private static string StripFrontMatter(string markdown)
    {
        var trimmed = markdown.TrimStart();
        if (!trimmed.StartsWith("---")) return markdown;

        var firstNewline = trimmed.IndexOf('\n');
        if (firstNewline < 0) return markdown;

        var closingIndex = trimmed.IndexOf("\n---", firstNewline);
        if (closingIndex < 0) return markdown;

        // Skip past the closing --- and any trailing newlines
        var bodyStart = closingIndex + 4; // length of "\n---"
        if (bodyStart < trimmed.Length && trimmed[bodyStart] == '\r') bodyStart++;
        if (bodyStart < trimmed.Length && trimmed[bodyStart] == '\n') bodyStart++;

        return trimmed[bodyStart..];
    }

    /// <summary>
    /// Wraps every &lt;img&gt; in the rendered HTML with a container span that
    /// provides the zoom-hint overlay used by the lightbox CSS and JS.
    /// Using &lt;span&gt; (inline by default, overridden to block in CSS) keeps
    /// the markup valid even when Markdig places images inside &lt;p&gt; tags.
    /// </summary>
    private static string WrapImages(string html)
    {
        // Language=Regex
        const string ZoomSvg =
            "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" " +
            "viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" " +
            "stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">" +
            "<circle cx=\"11\" cy=\"11\" r=\"8\"/>" +
            "<line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"/>" +
            "<line x1=\"11\" y1=\"8\" x2=\"11\" y2=\"14\"/>" +
            "<line x1=\"8\" y1=\"11\" x2=\"14\" y2=\"11\"/>" +
            "</svg>";

        return Regex.Replace(
            html,
            @"<img([^>]*?)(?:\s*/?)?>",
            $"<span class=\"build-img-wrap\"><img$1><span class=\"build-img-hint\" aria-hidden=\"true\">{ZoomSvg}</span></span>");
    }

    /// <summary>
    /// Rewrites relative image paths in markdown syntax (![alt](relative))
    /// to full CDN URLs before the markdown is parsed.
    /// </summary>
    private string RewriteRelativeImages(string markdown, string slug)
    {
        var cdnBase = $"{RawBase}/builds/{Uri.EscapeDataString(slug)}";
        return Regex.Replace(
            markdown,
            @"!\[([^\]]*)\]\((?!https?://|//)([^)]+)\)",
            m =>
            {
                var alt  = m.Groups[1].Value;
                var path = m.Groups[2].Value.TrimStart('.', '/');
                return $"![{alt}]({cdnBase}/{path})";
            });
    }

    /// <summary>
    /// Rewrites bare relative <c>href</c> values in rendered HTML — those with
    /// no protocol, no leading slash, and no fragment-only form — to absolute
    /// Blazor routes (<c>/builds/{slug}/{stem}</c>).
    /// This turns internal sub-page links like <c>[Print Settings](print-settings)</c>
    /// into proper SPA navigation targets instead of broken relative URLs.
    /// </summary>
    private static string RewriteRelativeLinks(string html, string slug)
    {
        // Match href="value" where value does NOT start with:
        //   https?://  (absolute HTTP/S)
        //   //         (protocol-relative)
        //   /          (root-relative – already correct)
        //   #          (fragment-only anchor)
        return Regex.Replace(
            html,
            @"href=""(?!https?://|//|[/#])([^""]+)""",
            m => $"href=\"/builds/{Uri.EscapeDataString(slug)}/{m.Groups[1].Value}\"");
    }

    /// <summary>
    /// Extracts the <c>title</c> field from a YAML front matter block.
    /// Returns null if the document has no front matter or no title field.
    /// </summary>
    private static string? ExtractFrontMatterTitle(string markdown)
    {
        var trimmed = markdown.TrimStart();
        if (!trimmed.StartsWith("---")) return null;

        var firstNewline = trimmed.IndexOf('\n');
        if (firstNewline < 0) return null;

        var closingIndex = trimmed.IndexOf("\n---", firstNewline);
        if (closingIndex < 0) return null;

        var frontMatter = trimmed[..closingIndex];
        var match = Regex.Match(frontMatter, @"^title:\s*""?([^""\r\n]+)""?\s*$", RegexOptions.Multiline);
        return match.Success ? match.Groups[1].Value.Trim() : null;
    }

    /// <summary>
    /// Converts a kebab-case slug (e.g. <c>print-settings</c>) to a
    /// human-readable title-cased string (<c>Print Settings</c>).
    /// Used as a fallback when no front matter title is available.
    /// </summary>
    private static string TitleCaseFromSlug(string slug) =>
        string.Join(" ", slug.Split('-')
            .Select(w => w.Length > 0 ? char.ToUpper(w[0]) + w[1..] : w));
}
